### ISSUE TITLE
GDAS-validation GSI build broken

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/JEDI-T2O#104]
Unable to compile GSI branch feature/gdas-validation due to inability to access CRTM library in `/work/noaa/da/eliu/JEDI-GDAS/crtm_v2.4.1-jedi.1-intel2022`

`feature/gdas-validation` `gsi_orion.lua` uses the following for CRTM

```
setenv("crtm_ROOT","/work/noaa/da/eliu/JEDI-GDAS/crtm_v2.4.1-jedi.1-intel2022/build")
setenv("crtm_VERSION","2.4.1-jedi.1")
setenv("CRTM_INC","/work/noaa/da/eliu/JEDI-GDAS/crtm_v2.4.1-jedi.1-intel2022/build/module")
setenv("CRTM_LIB","/work/noaa/da/eliu/JEDI-GDAS/crtm_v2.4.1-jedi.1-intel2022/build/lib/libcrtm_static.a")
setenv("CRTM_FIX","/work2/noaa/da/cmartin/GDASApp/fix/crtm/2.4.0")
```

`CRTM_INC` and `CRTM_LIB` are not accessible due to permission restrictions

```
Orion-login-2:/work2/noaa/da/rtreadon/gdas-validation/global-workflow/sorc/gsi_enkf.fd$ ls -l /work/noaa/da/eliu/JEDI-GDAS/crtm_v2.4.1-jedi.1-intel2022/build/module /work/noaa/da/eliu/JEDI-GDAS/crtm_v2.4.1-jedi.1-intel2022/build/lib/libcrtm_static.a
ls: cannot access /work/noaa/da/eliu/JEDI-GDAS/crtm_v2.4.1-jedi.1-intel2022/build/module: Permission denied
ls: cannot access /work/noaa/da/eliu/JEDI-GDAS/crtm_v2.4.1-jedi.1-intel2022/build/lib/libcrtm_static.a: Permission denied
```
Directory `/work/noaa/da/eliu/JEDI-GDAS` is only accessible to eliu 
```
drwx--S--- 32 eliu da 4096 Nov 27 18:22 JEDI-GDAS`
```

@emilyhcliu , please chmod `/work/noaa/da/eliu/JEDI-GDAS` to allow others to access this directory.

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , please chmod `/work/noaa/da/eliu/JEDI-GDAS` so others may access the contents of this directory.  You are the only person who can currently access this directory:  `drwx--S--- 32 eliu da 4096 Nov 27 18:22 JEDI-GDAS`.

We can not build GSI branch [`feature/gdas-validation`](https://github.com/NOAA-EMC/GSI/tree/feature/gdas-validation) due to permission restrictions on `/work/noaa/da/eliu/JEDI-GDAS`

**Comment by RussTreadon-NOAA** [comment]
@emilyhcliu , please chmod `/work/noaa/da/eliu/JEDI-GDAS` so others may access the contents of this directory. You are the only person who can currently access this directory: `drwx--S--- 32 eliu da 4096 Nov 27 18:22 JEDI-GDAS`.

We can not build GSI branch [`feature/gdas-validation`](https://github.com/NOAA-EMC/GSI/tree/feature/gdas-validation) due to permission restrictions on `/work/noaa/da/eliu/JEDI-GDAS`

**Comment by emilyhcliu** [comment]
@RussTreadon-NOAA I am sorry, I missed this thread of GitHub messages.  I just corrected the permission.

**Comment by RussTreadon-NOAA** [comment]
Working copy of GSI `feature/gdas-validation` successfully built on Orion.  Thank you @emilyhcliu for changing permissions on your CRTM installation.
