### ISSUE TITLE
Add 'ex-script' for UFSDA atm post

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/JEDI-T2O#11]

**Comment by RussTreadon-NOAA** [comment]
Work done in [feature/ex_scripts](https://github.com/NOAA-EMC/JEDI-T2O/tree/feature/ex_scripts) and merged into [develop](https://github.com/NOAA-EMC/JEDI-T2O/tree/develop).   Therefore, delete `feature/ex_scripts` at https://github.com/NOAA-EMC/JEDI-T2O/commit/83dcb8e8a138479c39e2c331f2a87938312c38f6 and close this issue.
