### ISSUE TITLE
Add 'ex-script' for UFSDA atm analysis run

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/JEDI-T2O#12]

**Comment by RussTreadon-NOAA** [comment]
Work done in [feature/ex_scripts](https://github.com/NOAA-EMC/JEDI-T2O/tree/feature/ex_scripts) and merged into [develop](https://github.com/NOAA-EMC/JEDI-T2O/tree/develop).   Therefore, delete `feature/ex_scripts` at 83dcb8e and close this issue.
