### ISSUE TITLE
AMSU-A Preliminary Evaluation

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/JEDI-T2O#3]
Issue to track preliminary evaluation of AMSU-A forward operator, quality control, and bias correction in UFO.

H(x) computation
- [ ] NOAA-15 H(x)
- [ ] NOAA-18 H(x)
- [ ] NOAA-19 H(x)
- [ ] MetOp-A H(x)
- [ ] MetOp-B H(x)
- [ ] MetOp-C H(x)

H(x) with bias correction
- [ ] NOAA-15 H(x) BC
- [ ] NOAA-18 H(x) BC
- [ ] NOAA-19 H(x) BC
- [ ] MetOp-A H(x) BC
- [ ] MetOp-B H(x) BC
- [ ] MetOp-C H(x) BC

QC procedures / counts
- [ ] NOAA-15 QC
- [ ] NOAA-18 QC
- [ ] NOAA-19 QC
- [ ] MetOp-A QC
- [ ] MetOp-B QC
- [ ] MetOp-C QC

**Comment by CoryMartin-NOAA** [comment]
A week of GSI diags have been produced on Orion and stored in the `ufo_eval_ref` R2D2 database under the experiment `gdas_f006_nofov_nonsst`.
For traditionalists, these are stored at: `/work/noaa/da/cmartin/UFO_eval_gfs/R2D2_readonly/ncdiag/ob/gdas_f006_nofov_nonsst/`

**Comment by CoryMartin-NOAA** [comment]
Some files for @emilyhcliu:
IODA obs: `/work/noaa/da/cmartin/UFO_eval_gfs/R2D2_readonly/ncdiag/ob/gdas_f006_nofov_nonsst/`
UFO BC files: `/work/noaa/stmp/cmartin/UFO_eval_gfs/R2D2_readonly/gsi/bc/oper/`
GSI diags/geovals: `/work/noaa/da/Cory.R.Martin/noscrub/UFO_eval/ROTDIRS/DARTH/allob_fh006_nonsstfov/`

Did I forget anything?

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA Thanks.  These files are all I need.
