### ISSUE TITLE
SSMIS Obs Validation

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/JEDI-T2O#48]
Need to validate observations from SSMIS and evaluate QC procedures in the SSMIS YAML file, as a SSMIS YAML file already exists in the GDASApp.

This issue will be used to track progress on validation of radiances in UFO for GDAS in four stages:

- [ ] HofX computation using GSI produced GeoVaLs
- [ ] QC count checks (and YAML changes) using GSI produced GeoVaLs
- [ ] Obs errors using GSI produced GeoVaLs
- [ ] HofX computation in FV3-JEDI

**Comment by azadeh-gh** [comment]
Hofx was identical
QC was almost identical (except 24 locations on lakes with > 2000 height that not rejected in GSI)

**Comment by azadeh-gh** [comment]
other than above 24 obs the obs errors difference in <1.5% of obs were:
1.19E-07
2.38E-07
3.58E-07
4.77E-07

**Comment by azadeh-gh** [comment]
All 4 stages checked and pull request sent to GDASApp repo.

**Comment by azadeh-gh** [comment]
Added 2 ssmis_f18.yaml file similar to ssmis_f17.yaml file and sent pull request to GDASApp repo
