### ISSUE TITLE
SEVIRI Obs Validation

### ISSUE THREAD

**Issue by XuanliLi-NOAA** [NOAA-EMC/JEDI-T2O#52]
This issue will be used to track progress on validation of SEVIRI observations in UFO for GDAS
A SEVIRI YAML file in GDASApp was copied from ufo/test/testinput/instrumentTests  to parm/atm/obs/testing.

The following will be tested:
 hofx computation using GSI produced GeoVaLs with run_ufo_hofx_test.sh script 
 QC count checks and YAML changes by comparing EffectiveQC against GsiEffectiveQC and PreQC 
 Obs errors using GSI produced GeoVaLs
 HofX computation in FV3-JEDI

**Comment by XuanliLi-NOAA** [comment]
HofX tested.
Added cloud_fraction in obs file and used it in the yaml file
Added clear sky standard deviation of Tb in the obs file and added standard deviation check in the yaml file
Edited the yaml file to include the gross check, terrain check, and background check. Also included the topography inflate error and transmittance top inflate error.

**Comment by XuanliLi-NOAA** [comment]
QC count checks (and YAML changes) using GSI produced GeoVaLs completed. The QC counts for all channels ( ch. 5 and ch. 6 in use; ch. 4, 7-11 monitored) are consistent with GSI.

**Comment by XuanliLi-NOAA** [comment]
QC steps for SEVIRI that have been added in the yaml file:
1. Surface type check: Use data on both land and sea for Ch. 5 and Ch. 6; Others only use data over sea
2. Terrain check: Discard data when terrain > 1000
3. Bounds check: Discard data for tb >1000 or < 0
4. Cloud detection IR
5. Ch. 9 tb standard deviation check
6. O-G gross check: Discard data when abs(tbc) > 2
7. Tz retrieval check
8. Use check

Inflate error:
1. Topography inflate
2. Transmittance at model top inflate
3. Surface Jacobian or emissivity check inflate

![SEVIRI-QC-Flowchart pptx (2)](https://user-images.githubusercontent.com/101414760/215344100-3e243ae6-26e2-4522-8957-0d458f261c4f.jpg)

Flow chart is also available here: 
https://docs.google.com/presentation/d/1gb23Al4Gg46ue2gcJ1tW6iexH_e79DVe/edit#slide=id.g200170e0fc1_1_0

**Comment by emilyhcliu** [comment]
Updated by @emilyhcliu 
![20230215 JEDI T2O (1)](https://user-images.githubusercontent.com/36091766/231325841-f07046cc-15be-400a-81d1-a6d3c0bf987a.png)

**Comment by emilyhcliu** [comment]
Updated by @emilyhcliu 

![20230215 JEDI T2O](https://user-images.githubusercontent.com/36091766/231325889-d721fffe-9eda-4b04-938a-44b952550689.png)
